name: aggregit
description: Records various metrics of the GitHub repository in a Firebase database.
branding:
  icon: bar-chart-2
  color: gray-dark
inputs:
  githubToken:
    required: true
    description: GitHub secret token
  project_id:
    required: true
    description: Firebase project id
  private_key:
    required: true
    description: Firebase private key
  client_email:
    required: true
    description: Firebase client email
  firebaseDbUrl:
    required: true
    description: Firebase database url
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.githubToken }}
    - ${{ inputs.project_id }}
    - ${{ inputs.private_key }}
    - ${{ inputs.client_email }}
    - ${{ inputs.firebaseDbUrl }}
