name: AggreGit
description: Records metrics of the GitHub repository in a Firebase database.
branding:
  icon: mail
  color: red
inputs:
  githubToken:
    required: true
  project_id:
    required: true
  private_key:
    required: true
  client_email:
    required: true
  firebaseDbUrl:
    required: true
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.githubToken }}
    - ${{ inputs.project_id }}
    - ${{ inputs.private_key }}
    - ${{ inputs.client_email }}
    - ${{ inputs.firebaseDbUrl }}
